name: hanet_webrtc_player
description: A WebRTC video player widget component for Flutter applications.
version: 0.0.1
homepage: https://github.com/dieunt/hanet_webrtc_player

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: hanet_webrtc_player
      ios:
        default_package: hanet_webrtc_player 