name: hanet_webrtc_player
description: A WebRTC video player widget component for Flutter applications.
version: 0.0.2
homepage: https://github.com/dieunt/hanet_webrtc_player
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.13.0
  shared_preferences: ^2.0.9
  path_provider: ^2.0.7
  event_bus: ^2.0.0  
  uuid: ^4.4.0
  video_player: ^2.8.1
  web_socket_channel: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0